### ISSUE TITLE
Nondescript Error during ddPCRclust step

### ISSUE THREAD

**Issue by todd-testerman** [bgbrink/ddPCRclust#6]
Hi Benedikt, 

I am receiving the below error when trying to run the main step:

`results2 = ddPCRclust(files, template)
Error in `[.data.frame`(template$template, which(template$template[, 1] ==  : 
  undefined columns selected`

My files and template files were accepted during the import step with no errors noted (after the fix from the other issue). I'll attach the updated template here again and an example file from the upload in case there is some problem with those. I ran the commands on the example data provided with no problems so I think the install worked properly. 

Thanks for any assistance!

Todd
[template_2.txt](https://github.com/bgbrink/ddPCRclust/files/3050693/template_2.txt)
[20190328_Triplex_flavo_test_H02_Amplitude.txt](https://github.com/bgbrink/ddPCRclust/files/3050694/20190328_Triplex_flavo_test_H02_Amplitude.txt)

**Comment by bgbrink** [comment]
Hi Todd,

sorry for the late response, I was on vacation last week.

There are two problems with your files:
First, it seems you are using tab-separated-values (tsv) instead of comma-separated-values (csv). ddPCRclust expects csv files (just replace all tabs `\t` with commas `,`).
Second, your template file only contains three columns (Marker 1 - Marker 3). ddPCRclust was built for multiplexed ddPCR experiments and always expects four columns in the template, in order to know which markers are empty. You can leave the fourth column empty by just adding another comma to each row except the header and the marker names.

I will try to make the package smarter about template import in the next version. It's not very intuitive right now, sorry about that.

**Comment by todd-testerman** [comment]
Hi Benedikt,

Thanks for the reply! 

I was actually using .csv files for the import into ddPCRclust but Github would only allow me to attach .tsv files for some reason...

The second point was definitely the problem! Import worked after I tried that and the processing steps finished. 

Thanks for the support!

Todd Testerman
